#!/usr/bin/env bash

enabled=$(<~/.clicker.bool)
if [[ "${enabled}" == true ]] ; then
  echo "false" >| ~/.clicker.bool
else
  echo "true" >| ~/.clicker.bool
  while true; do
    xdotool click --repeat 4 --delay 62 $1
    enabled=$(<~/.clicker.bool)
    if [[ $enabled == false ]]; then
      break
    fi
  done
fi
