name: NixOS
concurrency: nixos

on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "NOTES.md"
      - ".gitignore"

jobs:
  build-mitama:
    runs-on: ubuntu-latest
    steps:
      - name: "Create Dir for Mounting moar Disk Space ❄"
        run: |
          sudo mkdir /nix

      - name: "Maximize Disk Space 1"
        run: |
          sudo rm -rf $AGENT_TOOLSDIRECTORY
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/local/lib/heroku
          sudo rm -rf /var/lib/docker/overlay2
          sudo rm -rf /home/linuxbrew
          sudo rm -rf /home/runner/.rustup

      - name: "Maximize Disk Space 2"
        uses: easimon/maximize-build-space@v8
        with:
          root-reserve-mb: 8192
          swap-size-mb: 1024
          build-mount-path: /nix
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - uses: actions/checkout@v3

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v12
        with:
          name: workflow-nixos-config
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Build NixOS config ❄️"
        run: |
          nix build .#nixosConfigurations.mitama.config.system.build.toplevel

      - name: "Check NixOS flake ❄️"
        run: |
          nix flake check

  build-dekomori:
    runs-on: ubuntu-latest
    steps:
      - name: "Create Dir for Mounting moar Disk Space ❄"
        run: |
          sudo mkdir /nix

      - name: "Maximize Disk Space 1"
        run: |
          sudo rm -rf $AGENT_TOOLSDIRECTORY
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/local/lib/heroku
          sudo rm -rf /var/lib/docker/overlay2
          sudo rm -rf /home/linuxbrew
          sudo rm -rf /home/runner/.rustup

      - name: "Maximize Disk Space 2"
        uses: easimon/maximize-build-space@v8
        with:
          root-reserve-mb: 8192
          swap-size-mb: 1024
          build-mount-path: /nix
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - uses: actions/checkout@v3

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v12
        with:
          name: workflow-nixos-config
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Build NixOS config ❄️"
        run: |
          nix build .#nixosConfigurations.dekomori.config.system.build.toplevel

      - name: "Check NixOS flake ❄️"
        run: |
          nix flake check
